export const spongeBobMemeData = [
    {
        emotionTags: ["sad"],
        isGif: false,
        image: "cookiememe.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "deadphonememe.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["confused","scared"],
        isGif: false,
        image: "fartingmspuffmeme.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["confused", "scared"],
        isGif: false,
        image: "mspuffscared.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "patrickhello.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "patrickhungry.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "patricklove.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["moody","dominant"],
        isGif: true,
        image: "planktonmeniacal.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["sad"],
        isGif: false,
        image: "sadmusicmeme.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "spongebuff.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "spongeexcited.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["happy","dominant"],
        isGif: true,
        image: "spongehappy.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "spongepatrickexcited.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["confused", "sad"],
        isGif: true,
        image: "spongepatrickthinking.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["confused", "sad"],
        isGif: false,
        image: "spongepolice.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "spongesad.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["insomniac", "scared"],
        isGif: false,
        image: "spongesleepanxiety.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["scared"],
        isGif: true,
        image: "spongethisisfine.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "spongetrip.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "spongeuglymeme.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "spongeworkingmeme.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["happy", "relaxed"],
        isGif: true,
        image: "squiddancing.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "squidhate.webp",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "squidsleepy.jpg",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["happy", "moody", "sad"],
        isGif: true,
        image: "squidspongeinteraction.gif",
        alt: "A SpongeBob Meme",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "textinngmeme.jpg",
        alt: "A SpongeBob Meme",
    },
]

